name: StupidBirdExpress
version: 0.0.1
description: |
  A minimal web app for the developer that doesn’t want to be confused by too much going on.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  mailer: ">=0.8.12 <0.9.0"
  args: any
