library client.field_name;


///actions list attributes

const int   ACTION_TURN = 0;
const int   ACTION_WALK = 1;
const int    ACTION_FLY = 2;
const int ACTION_PADDLE = 3;
const int  ACTION_HATCH = 4;

const int      ACTION_TYPE = 0;
const int     ACTION_TIMES = 1;
const int ACTION_DIRECTION = 2;
const int     ACTION_STEPS = 1;

const int DEGREE_UNIT = 45;


///game timer attributes

const int       TIME_UNIT_PER_IMG = 1;
const int       TIME_UNIT_PER_POS = 4;
const int TIME_UNIT_PER_HIGHLIGHT = 4;
const int               STEP_UNIT = 45;


///map attributes

const int          MAP_WIDTH = 14;
const int         MAP_HEIGHT = 12;
const int MAINACTOR_POS_LEFT = 0;
const int  MAINACTOR_POS_TOP = 0;

const int            MAP_BOAT = 0;
const int   MAP_FLIPPED_ARBOR = 1;
const int    MAP_FLIPPED_BUSH = 2;
const int   MAP_FLIPPED_STRAW = 3;
const int  MAP_UNFLIPPED_TREE = 4;
const int MAP_UNFLIPPED_ARBOR = 5;
const int          MAP_GROUND = 6;
const int           MAP_RIVER = 7;
const int  MAP_UNFLIPPED_WALL = 8;
const int             MAP_EGG = 9;

const int MAP_POS_ACTION_TYPE = 2;
const int MAP_ITEMS_COUNT = 4;


const int ERROR_OUT_OF_BORDER = 0;
const int         ERROR_DRAWN = 1;
const int      ERROR_HIT_WALL = 2;
const int     ERROR_BREAK_EGG = 3;
const int        ERROR_NO_EGG = 4;

///img url

const String   BOAT = 'url(../../source/boat.png)';
const String  ARBOR = 'url(../../source/arbor.png)';
const String   BUSH = 'url(../../source/bush.png)';
const String  STRAW = 'url(../../source/straw.png)';
const String TREE_1 = 'url(../../source/tree1.png)';
const String TREE_2 = 'url(../../source/tree2.png)';
const String TREE_3 = 'url(../../source/tree3.png)';
const String TREE_4 = 'url(../../source/tree4.png)';

final List<String> BlockImgs = [BOAT, ARBOR, BUSH, STRAW, TREE_1, TREE_2, TREE_3, TREE_4];

///static map

final List<List<int>> Map_1 = 
[[        MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND, 		  MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND],
 [        MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND, 		  MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND],
 [        MAP_GROUND,         MAP_GROUND, MAP_UNFLIPPED_TREE,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND, 		  MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND, MAP_UNFLIPPED_TREE,         MAP_GROUND,         MAP_GROUND],
 [        MAP_GROUND,         MAP_GROUND, MAP_UNFLIPPED_TREE,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND, 		  MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND, MAP_UNFLIPPED_TREE,         MAP_GROUND,         MAP_GROUND],
 [        MAP_GROUND,         MAP_GROUND, MAP_UNFLIPPED_TREE, MAP_UNFLIPPED_TREE, MAP_UNFLIPPED_TREE,   MAP_FLIPPED_BUSH,   MAP_FLIPPED_BUSH, MAP_UNFLIPPED_TREE, MAP_UNFLIPPED_TREE, MAP_UNFLIPPED_TREE, MAP_UNFLIPPED_TREE, MAP_UNFLIPPED_TREE,         MAP_GROUND,         MAP_GROUND],
 [        MAP_GROUND,         MAP_GROUND, MAP_UNFLIPPED_TREE,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND, MAP_UNFLIPPED_TREE,         MAP_GROUND,         MAP_GROUND],
 [        MAP_GROUND,         MAP_GROUND, MAP_UNFLIPPED_TREE,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND, MAP_UNFLIPPED_TREE,         MAP_GROUND,         MAP_GROUND],
 [        MAP_GROUND,         MAP_GROUND, MAP_UNFLIPPED_TREE, MAP_UNFLIPPED_TREE, MAP_UNFLIPPED_TREE, MAP_UNFLIPPED_TREE, MAP_UNFLIPPED_TREE, MAP_UNFLIPPED_TREE,   MAP_FLIPPED_BUSH,   MAP_FLIPPED_BUSH, MAP_UNFLIPPED_TREE, MAP_UNFLIPPED_TREE,         MAP_GROUND,         MAP_GROUND],
 [        MAP_GROUND,         MAP_GROUND, MAP_UNFLIPPED_TREE,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND, MAP_UNFLIPPED_TREE,         MAP_GROUND,         MAP_GROUND],
 [MAP_UNFLIPPED_WALL,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND, MAP_UNFLIPPED_WALL],
 [        MAP_GROUND, MAP_UNFLIPPED_WALL,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND, MAP_UNFLIPPED_WALL,         MAP_GROUND],
 [        MAP_GROUND,         MAP_GROUND, MAP_UNFLIPPED_WALL,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND, MAP_UNFLIPPED_WALL,         MAP_GROUND,         MAP_GROUND]];

final List<List<int>> Map_2 = 
[[MAP_RIVER,           MAP_RIVER,           MAP_RIVER, MAP_RIVER, MAP_RIVER, MAP_RIVER, MAP_GROUND, MAP_GROUND, MAP_GROUND, MAP_GROUND, MAP_UNFLIPPED_TREE, MAP_UNFLIPPED_TREE, MAP_UNFLIPPED_TREE, MAP_UNFLIPPED_TREE],
 [MAP_RIVER, MAP_UNFLIPPED_ARBOR, MAP_UNFLIPPED_ARBOR, MAP_RIVER, MAP_RIVER, MAP_RIVER,  MAP_RIVER, MAP_GROUND, MAP_GROUND, MAP_GROUND,         MAP_GROUND, MAP_UNFLIPPED_TREE, MAP_UNFLIPPED_TREE, MAP_UNFLIPPED_TREE],
 [MAP_RIVER,   MAP_FLIPPED_ARBOR, MAP_UNFLIPPED_ARBOR, MAP_RIVER, MAP_RIVER, MAP_RIVER,  MAP_RIVER,  MAP_RIVER, MAP_GROUND, MAP_GROUND,         MAP_GROUND, MAP_UNFLIPPED_TREE, MAP_UNFLIPPED_TREE, MAP_UNFLIPPED_TREE],
 [MAP_RIVER,           MAP_RIVER,           MAP_RIVER, MAP_RIVER, MAP_RIVER, MAP_RIVER,  MAP_RIVER,  MAP_RIVER, MAP_GROUND, MAP_GROUND,         MAP_GROUND, MAP_UNFLIPPED_TREE, MAP_UNFLIPPED_TREE, MAP_UNFLIPPED_TREE],
 [MAP_RIVER,           MAP_RIVER,           MAP_RIVER, MAP_RIVER, MAP_RIVER, MAP_RIVER,  MAP_RIVER,  MAP_RIVER, MAP_GROUND, MAP_GROUND,         MAP_GROUND,         MAP_GROUND, MAP_UNFLIPPED_TREE, MAP_UNFLIPPED_TREE],
 [MAP_RIVER,           MAP_RIVER,           MAP_RIVER, MAP_RIVER, MAP_RIVER, MAP_RIVER,  MAP_RIVER,  MAP_RIVER, MAP_GROUND, MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND, MAP_UNFLIPPED_TREE],
 [MAP_RIVER,           MAP_RIVER,           MAP_RIVER, MAP_RIVER, MAP_RIVER, MAP_RIVER,  MAP_RIVER,   MAP_BOAT, MAP_GROUND, MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND],
 [MAP_RIVER,           MAP_RIVER,           MAP_RIVER, MAP_RIVER, MAP_RIVER, MAP_RIVER,  MAP_RIVER,  MAP_RIVER,  MAP_RIVER, MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND],
 [MAP_RIVER,           MAP_RIVER,           MAP_RIVER, MAP_RIVER, MAP_RIVER, MAP_RIVER,  MAP_RIVER,  MAP_RIVER,  MAP_RIVER,  MAP_RIVER,          MAP_RIVER,         MAP_GROUND,         MAP_GROUND,         MAP_GROUND],
 [MAP_RIVER,           MAP_RIVER,           MAP_RIVER, MAP_RIVER, MAP_RIVER, MAP_RIVER,  MAP_RIVER,  MAP_RIVER,  MAP_RIVER,  MAP_RIVER,          MAP_RIVER,          MAP_RIVER,         MAP_GROUND,         MAP_GROUND],
 [MAP_RIVER,           MAP_RIVER,           MAP_RIVER, MAP_RIVER, MAP_RIVER, MAP_RIVER,  MAP_RIVER,  MAP_RIVER,  MAP_RIVER,  MAP_RIVER,          MAP_RIVER,          MAP_RIVER,         MAP_GROUND,         MAP_GROUND],
 [MAP_RIVER,           MAP_RIVER,           MAP_RIVER, MAP_RIVER, MAP_RIVER, MAP_RIVER,  MAP_RIVER,  MAP_RIVER,  MAP_RIVER,  MAP_RIVER,          MAP_RIVER,          MAP_RIVER,         MAP_GROUND,         MAP_GROUND]];


final List<List<int>> Map_3 = 
[[MAP_GROUND, MAP_GROUND,  MAP_RIVER, MAP_GROUND, MAP_GROUND,        MAP_GROUND,        MAP_GROUND,        MAP_GROUND,        MAP_GROUND,        MAP_GROUND,        MAP_GROUND,        MAP_GROUND, MAP_GROUND, MAP_GROUND],
 [MAP_GROUND, MAP_GROUND,  MAP_RIVER, MAP_GROUND, MAP_GROUND,        MAP_GROUND,        MAP_GROUND,        MAP_GROUND,        MAP_GROUND,        MAP_GROUND,        MAP_GROUND,        MAP_GROUND, MAP_GROUND, MAP_GROUND],
 [MAP_GROUND, MAP_GROUND,  MAP_RIVER, MAP_GROUND, MAP_GROUND, MAP_FLIPPED_STRAW, MAP_FLIPPED_STRAW, MAP_FLIPPED_STRAW, MAP_FLIPPED_STRAW, MAP_FLIPPED_STRAW, MAP_FLIPPED_STRAW, MAP_FLIPPED_STRAW, MAP_GROUND, MAP_GROUND],
 [MAP_GROUND, MAP_GROUND,  MAP_RIVER, MAP_GROUND, MAP_GROUND, MAP_FLIPPED_STRAW,        MAP_GROUND,        MAP_GROUND,        MAP_GROUND,        MAP_GROUND,        MAP_GROUND, MAP_FLIPPED_STRAW, MAP_GROUND, MAP_GROUND],
 [MAP_GROUND, MAP_GROUND,  MAP_RIVER, MAP_GROUND, MAP_GROUND, MAP_FLIPPED_STRAW,        MAP_GROUND,        MAP_GROUND,        MAP_GROUND,        MAP_GROUND,        MAP_GROUND, MAP_FLIPPED_STRAW, MAP_GROUND, MAP_GROUND],
 [MAP_GROUND, MAP_GROUND,  MAP_RIVER, MAP_GROUND, MAP_GROUND, MAP_FLIPPED_STRAW,        MAP_GROUND,        MAP_GROUND,        MAP_GROUND,        MAP_GROUND,        MAP_GROUND, MAP_FLIPPED_STRAW, MAP_GROUND, MAP_GROUND],
 [MAP_GROUND, MAP_GROUND,  MAP_RIVER, MAP_GROUND, MAP_GROUND, MAP_FLIPPED_STRAW, MAP_FLIPPED_STRAW, MAP_FLIPPED_STRAW,        MAP_GROUND, MAP_FLIPPED_STRAW, MAP_FLIPPED_STRAW, MAP_FLIPPED_STRAW, MAP_GROUND, MAP_GROUND],
 [MAP_GROUND, MAP_GROUND,  MAP_RIVER, MAP_GROUND, MAP_GROUND,        MAP_GROUND,        MAP_GROUND,        MAP_GROUND,        MAP_GROUND,        MAP_GROUND,        MAP_GROUND,        MAP_GROUND, MAP_GROUND, MAP_GROUND],
 [MAP_GROUND, MAP_GROUND,  MAP_RIVER, MAP_GROUND, MAP_GROUND,        MAP_GROUND,        MAP_GROUND,        MAP_GROUND,        MAP_GROUND,        MAP_GROUND,        MAP_GROUND,        MAP_GROUND, MAP_GROUND, MAP_GROUND],
 [MAP_GROUND, MAP_GROUND,  MAP_RIVER,  MAP_RIVER,  MAP_RIVER,         MAP_RIVER,         MAP_RIVER,         MAP_RIVER,         MAP_RIVER,         MAP_RIVER,         MAP_RIVER,         MAP_RIVER,  MAP_RIVER,  MAP_RIVER],
 [MAP_GROUND, MAP_GROUND, MAP_GROUND, MAP_GROUND, MAP_GROUND,        MAP_GROUND,        MAP_GROUND,        MAP_GROUND,        MAP_GROUND,        MAP_GROUND,        MAP_GROUND,        MAP_GROUND, MAP_GROUND, MAP_GROUND],
 [MAP_GROUND, MAP_GROUND, MAP_GROUND, MAP_GROUND, MAP_GROUND,        MAP_GROUND,        MAP_GROUND,        MAP_GROUND,        MAP_GROUND,        MAP_GROUND,        MAP_GROUND,        MAP_GROUND, MAP_GROUND, MAP_GROUND]];

